# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('faculty', models.CharField(choices=[('SCIENCE', 'SCIENCE'), ('SOCIAL SCIENCE', 'SOCIAL SCIENCE'), ('ENGINEERING', 'ENGINEERING')], default='fs', max_length=200)),
                ('department', models.CharField(choices=[('COMPUTER SCIENCE', 'COMPUTER SCIENCE'), ('COMPUTER INFORMATION SYSTEM', 'COMPUTER INFORMATION SYSTEM'), ('ELECTRICAL ENGINEERING', 'ELECTRICAL ENGINEERING')], default='cs', max_length=100)),
                ('type', models.CharField(choices=[('THESIS/DESSERTATION', 'THESIS/DESSERTATION'), ('BSc PROJECT', 'BSc PROJECT'), ('JOURNALS', 'JOURNALS')], default='BSc PROJECT', max_length=100)),
                ('authors', models.CharField(max_length=200)),
                ('attachment', models.FileField(upload_to='uploads/%Y/')),
                ('abstract', models.TextField(default='', max_length=5000)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Failed', 'Failed')], default='Pending', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pumas.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
