# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
