# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumas', '0002_auto_20171122_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='plagiarism_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('failed', 'failed')], default='pending', max_length=40),
        ),
    ]
