# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pumas', '0003_auto_20171123_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
