# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumas', '0008_auto_20171129_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
